name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build-test-deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend-astro

      - name: Run prod build
        run: npm run build
        working-directory: ./frontend-astro

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./frontend-astro/dist

      - name: Publish master to Netlify only on a 'push' to master
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npm run netlify:deploy:prod -- --message "Deployed from GithubActions commit(github_sha)-${GITHUB_SHA}"
        working-directory: ./frontend-astro
